import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const canvaSans = localFont({ src: './fonts/CanvaSans-Regular.woff2', variable: '--font-canva-sans' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className={`${canvaSans.variable} h-full antialiased`}>
            <body className='min-h-full flex flex-col' style={canvaSans.style}>
                {children}
            </body>
        </html>
    )
}
